# NumPy Exercise (5 points)

Create a 2x10 array (two rows and 10 columns) `ary0` of 10 zeros, using integer numbers as data type. 

In [102]:
# Your code here
import numpy as np
ary0 = np.zeros((2, 10), dtype = int)
print("ary0 = ",ary0)

ary0 =  [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


Create an array `ary1` of 10 ones using float numbers, and an array `aray3` of 10 threes using integer numbers. Concatenate the three arrays (ary0, ary1,ary3) horiztonally to obtain a 4x10 array called `ary4`.

In [103]:
# Your code here
ary1 = np.ones(10, dtype = float)
print("ary1 = ",ary1)
aray3 = np.ones(10, dtype = int)*3
print("aray3 = ",aray3)
#To horizontally stack arrays:
ary4 = np.vstack((ary0, ary1, aray3))

ary1 =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
aray3 =  [3 3 3 3 3 3 3 3 3 3]


Display the data type of `ary4`. Why it is that data type?

In [104]:
# Your code here
print("Array ary4 = ",ary4)
print("Data type of array 'ary4' = ",ary4.dtype)
'''The data type of the array is float as one of the arrays being concatenated 
was float thus to avoid information loss all arrays were concatenated and converted to float.'''

Array ary4 =  [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]
Data type of array 'ary4' =  float64


'The data type of the array is float as one of the arrays being concatenated \nwas float thus to avoid information loss all arrays were concatenated and converted to float.'

Create a numpy array of integers from 10 to 50.

In [105]:
# Your code here
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

Create a numpy array of the "even" integers from 5 to 29.

In [106]:
# Your code here
np.arange(6, 30, 2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

Create a 3x4 array with values ranging from 0 to 12, using `arange` and `reshape`.

In [107]:
# Your code here
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Generate an array of 15 random numbers sampled from a standard normal distribution with 3 mean and 12 standard deviation, by applying a Random State to the random number generator. 

In [108]:
# Your code here
np.random.seed(32)
a_normal = 3 + 12 * np.random.randn(15)
print("Standard normal distribution with 3 mean and 12 standard deviation =\n",a_normal)

Standard normal distribution with 3 mean and 12 standard deviation =
 [-1.18673341 14.8044412   9.97107397  3.84341329 12.33039212  9.98350494
 20.66148632 22.95817211 -0.13412546 -5.26412175 -5.33907915 26.28508152
 24.66498228  8.47576622 -3.89774448]


Display the indices of the elements of the above array sorted in ascending order. 

In [109]:
# Your code here
print("The indices of above array sorted in ascending order =",np.argsort(a_normal))

The indices of above array sorted in ascending order = [10  9 14  0  8  3 13  2  5  4  1  6  7 12 11]


Generate a 4x5 array called `ary4` of random numbers sampled from a uniform distribution. Use the random seed `12` to ensure reproducibility. 

In [110]:
# Your code here
np.random.seed(12)
ary4 = np.random.uniform(size = (4, 5))
print("Random numbers sampled from a uniform distribution b/w 0 and 1 =\n",ary4)

Random numbers sampled from a uniform distribution b/w 0 and 1 =
 [[0.15416284 0.7400497  0.26331502 0.53373939 0.01457496]
 [0.91874701 0.90071485 0.03342143 0.95694934 0.13720932]
 [0.28382835 0.60608318 0.94422514 0.85273554 0.00225923]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.16071675]]


Display the average values of the rows of `ary4`.

In [111]:
# Your code here
print("Average of rows of the array ary4 =",np.average(ary4, axis = 1))

Average of rows of the array ary4 = [0.34116838 0.58940839 0.53782629 0.4974984 ]


Display the index of the minimum element in each column in `ary4`. 

In [112]:
# Your code here
print("Index of the minimum element in each column in ary4 =",np.argmin(ary4, axis = 0))

Index of the minimum element in each column in ary4 = [0 3 1 0 2]


Create a Boolean mask of the elements in `ary4` that are in the range between 0.3 and 0.8, and afterward use the mask to extract the elements into a new array `ary5`.

In [113]:
# Your code here
mask = (ary4>0.3) & (ary4<0.8)
ary5 = ary4[mask]
print("New array ary5 =",ary5)

New array ary5 = [0.7400497  0.53373939 0.60608318 0.52122603 0.55203763 0.48537741
 0.76813415]


Flatten `ary5` using both `flatten()` and `ravel()` and check if the resulting arrays are views of `ary5` (i.e., share the same memory).

### Masking converted the 2-D array into a 1-D array and flatten does not make any changes to an already 1-D array. So I have tried to mask using np.where.

In [114]:
ary5 = np.where(mask, ary4, 0)
print("ary5 =",ary5)
#Ravel can work on any object that can be parsed and would only return a view.
ary5_ravel = ary5.ravel()
print("Ravel =",ary5_ravel)
#Flatten only works on numpy arrays and would return a copy.
#The memory locations of the results are different.
ary5_flatten = ary5.flatten()
print("Flatten =",ary5_flatten)

#Check the base attribute
print("Check the base attribute =",ary5_flatten.base is ary5_ravel)

#Check memory
print("Check share memory =",np.may_share_memory(ary5_ravel, ary5_flatten))

ary5 = [[0.         0.7400497  0.         0.53373939 0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.60608318 0.         0.         0.        ]
 [0.52122603 0.55203763 0.48537741 0.76813415 0.        ]]
Ravel = [0.         0.7400497  0.         0.53373939 0.         0.
 0.         0.         0.         0.         0.         0.60608318
 0.         0.         0.         0.52122603 0.55203763 0.48537741
 0.76813415 0.        ]
Flatten = [0.         0.7400497  0.         0.53373939 0.         0.
 0.         0.         0.         0.         0.         0.60608318
 0.         0.         0.         0.52122603 0.55203763 0.48537741
 0.76813415 0.        ]
Check the base attribute = False
Check share memory = False


Create an array of 40 linearly spaced points between 3 and 5.

In [115]:
# Your code here
print("Array of 40 linearly spaced points between 3 and 5 =\n",np.linspace(3, 5, num = 40))

Array of 40 linearly spaced points between 3 and 5 =
 [3.         3.05128205 3.1025641  3.15384615 3.20512821 3.25641026
 3.30769231 3.35897436 3.41025641 3.46153846 3.51282051 3.56410256
 3.61538462 3.66666667 3.71794872 3.76923077 3.82051282 3.87179487
 3.92307692 3.97435897 4.02564103 4.07692308 4.12820513 4.17948718
 4.23076923 4.28205128 4.33333333 4.38461538 4.43589744 4.48717949
 4.53846154 4.58974359 4.64102564 4.69230769 4.74358974 4.79487179
 4.84615385 4.8974359  4.94871795 5.        ]


For the given array `mat`, in the following cells apply slicing operations to replicate the displayed outputs.

In [116]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [117]:
# Your code here
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [118]:
# Your code here
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [119]:
# Your code here
mat[1:3,2::2]

array([[ 8, 10],
       [13, 15]])

In [120]:
# Your code here
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])